"""The three delivery scripts must bundle the same licence texts.

`meridian/main.py` reads two licence files at startup and `_read_text`
degrades to "Licence text unavailable." rather than raising, so a script that
omits one produces a build that starts cleanly and renders that line in place
of a licence. That failure is invisible to every other test in this suite,
because nothing here asserts over a built bundle.

`build_resources.LICENCE_FILES` is the single source of truth. These tests
hold the two consumers it cannot reach by import to the same list: the Flatpak
manifest, which is generated by a shell heredoc, and the application's own
reader, which must not import a build script.
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path
from types import ModuleType

_ROOT = Path(__file__).parent.parent.parent


def _load_build_resources() -> ModuleType:
    """Load the root build module without putting the root on `sys.path`."""
    spec = importlib.util.spec_from_file_location(
        "build_resources", _ROOT / "build_resources.py"
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


LICENCE_FILES: tuple[str, ...] = _load_build_resources().LICENCE_FILES


def test_every_bundled_licence_exists() -> None:
    missing = [name for name in LICENCE_FILES if not (_ROOT / name).is_file()]
    assert (
        not missing
    ), "Licence files listed but absent from the repository:\n" + "\n".join(missing)


def test_flatpak_manifest_installs_every_licence() -> None:
    script = (_ROOT / "build_flatpak.sh").read_text(encoding="utf-8")
    missing = [
        name for name in LICENCE_FILES if f"install -Dm644 {name} " not in script
    ]
    assert not missing, (
        "build_flatpak.sh does not install these licence files:\n"
        + "\n".join(missing)
        + "\nAdd an `install -Dm644 <name>` line for each."
    )


def test_python_delivery_scripts_hold_no_licence_literal() -> None:
    """Both must go through the shared list rather than naming files again."""
    offenders = []
    for name in ("buildexe.py", "builddmg.py"):
        source = (_ROOT / name).read_text(encoding="utf-8")
        literals = re.findall(r"[\"'](LICENSE[^\"']*)[\"']", source)
        if literals:
            offenders.append(f"{name}: {sorted(set(literals))}")
    assert not offenders, (
        "Delivery scripts naming a licence file directly (use LICENCE_FILES):\n"
        + "\n".join(offenders)
    )


def test_application_reads_only_bundled_licences() -> None:
    """`main.py` must not read a licence no delivery script ships."""
    source = (_ROOT / "meridian" / "main.py").read_text(encoding="utf-8")
    read = re.findall(r"_\w*LICENCE_FILE\s*=\s*[\"']([^\"']+)[\"']", source)
    assert read, "Found no licence filenames in meridian/main.py"
    unbundled = [name for name in read if name not in LICENCE_FILES]
    assert not unbundled, (
        "meridian/main.py reads licence files no delivery script bundles:\n"
        + "\n".join(unbundled)
    )
